apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: helm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: helm-storage
  resources:
    requests:
      storage: 30Gi